//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.13 at 01:03:38 AM CET 
//


package ch.bfh.proj1.trafficlightsimulator.xmlLoader;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConfigType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConfigType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Junctions" type="{http://www.bfh.ch/project1/2014/I2R/TrafficLightConfigSchema}JunctionsType"/>
 *         &lt;element name="Streets" type="{http://www.bfh.ch/project1/2014/I2R/TrafficLightConfigSchema}StreetsType"/>
 *         &lt;element name="Lanes" type="{http://www.bfh.ch/project1/2014/I2R/TrafficLightConfigSchema}LanesType"/>
 *         &lt;element name="Routes" type="{http://www.bfh.ch/project1/2014/I2R/TrafficLightConfigSchema}RoutesType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConfigType", propOrder = {
    "junctions",
    "streets",
    "lanes",
    "routes"
})

@XmlRootElement
public class ConfigType {

    @XmlElement(name = "Junctions", required = true)
    protected JunctionsType junctions;
    @XmlElement(name = "Streets", required = true)
    protected StreetsType streets;
    @XmlElement(name = "Lanes", required = true)
    protected LanesType lanes;
    @XmlElement(name = "Routes", required = true)
    protected RoutesType routes;

    /**
     * Gets the value of the junctions property.
     * 
     * @return
     *     possible object is
     *     {@link JunctionsType }
     *     
     */
    public JunctionsType getJunctions() {
        return junctions;
    }

    /**
     * Sets the value of the junctions property.
     * 
     * @param value
     *     allowed object is
     *     {@link JunctionsType }
     *     
     */
    public void setJunctions(JunctionsType value) {
        this.junctions = value;
    }

    /**
     * Gets the value of the streets property.
     * 
     * @return
     *     possible object is
     *     {@link StreetsType }
     *     
     */
    public StreetsType getStreets() {
        return streets;
    }

    /**
     * Sets the value of the streets property.
     * 
     * @param value
     *     allowed object is
     *     {@link StreetsType }
     *     
     */
    public void setStreets(StreetsType value) {
        this.streets = value;
    }

    /**
     * Gets the value of the lanes property.
     * 
     * @return
     *     possible object is
     *     {@link LanesType }
     *     
     */
    public LanesType getLanes() {
        return lanes;
    }

    /**
     * Sets the value of the lanes property.
     * 
     * @param value
     *     allowed object is
     *     {@link LanesType }
     *     
     */
    public void setLanes(LanesType value) {
        this.lanes = value;
    }

    /**
     * Gets the value of the routes property.
     * 
     * @return
     *     possible object is
     *     {@link RoutesType }
     *     
     */
    public RoutesType getRoutes() {
        return routes;
    }

    /**
     * Sets the value of the routes property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoutesType }
     *     
     */
    public void setRoutes(RoutesType value) {
        this.routes = value;
    }

}
