//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.13 at 01:03:38 AM CET 
//


package ch.bfh.proj1.trafficlightsimulator.xmlLoader;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ch.bfh.project1._2014.i2r.trafficlightconfigschema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TrafficLightConfig_QNAME = new QName("http://www.bfh.ch/project1/2014/I2R/TrafficLightConfigSchema", "TrafficLightConfig");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ch.bfh.project1._2014.i2r.trafficlightconfigschema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConfigType }
     * 
     */
    public ConfigType createConfigType() {
        return new ConfigType();
    }

    /**
     * Create an instance of {@link RouteType }
     * 
     */
    public RouteType createRouteType() {
        return new RouteType();
    }

    /**
     * Create an instance of {@link JunctionType }
     * 
     */
    public JunctionType createJunctionType() {
        return new JunctionType();
    }

    /**
     * Create an instance of {@link RoutesType }
     * 
     */
    public RoutesType createRoutesType() {
        return new RoutesType();
    }

    /**
     * Create an instance of {@link StreetsType }
     * 
     */
    public StreetsType createStreetsType() {
        return new StreetsType();
    }

    /**
     * Create an instance of {@link LanesType }
     * 
     */
    public LanesType createLanesType() {
        return new LanesType();
    }

    /**
     * Create an instance of {@link JunctionsType }
     * 
     */
    public JunctionsType createJunctionsType() {
        return new JunctionsType();
    }

    /**
     * Create an instance of {@link StreetType }
     * 
     */
    public StreetType createStreetType() {
        return new StreetType();
    }

    /**
     * Create an instance of {@link LaneType }
     * 
     */
    public LaneType createLaneType() {
        return new LaneType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConfigType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bfh.ch/project1/2014/I2R/TrafficLightConfigSchema", name = "TrafficLightConfig")
    public JAXBElement<ConfigType> createTrafficLightConfig(ConfigType value) {
        return new JAXBElement<ConfigType>(_TrafficLightConfig_QNAME, ConfigType.class, null, value);
    }

}
